# Generated by Django 4.2.7 on 2023-11-12 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_article_content_remove_article_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Image',
        ),
    ]
