# Generated by Django 4.2.7 on 2023-11-13 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_classifiedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifiedimage',
            name='title',
        ),
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
