# Generated by Django 4.2.7 on 2023-11-17 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_classifiedimage_title_remove_image_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifiedimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='classifiedimage',
            name='score',
        ),
    ]
